# base_config.yaml

location: Richmond_city_VA
year: 2022
bad_types: "'bg_centroid'"
beta: -1
time_limit: 360000  # 100 hours
capacity: 1.8
precincts_open: 'null'
max_min_mult: 5  # scalar >= 1
maxpctnew: 1  # in interval [0,1]
minpctold: .8  # in interval [0,1]
penalized_sites: null
config_name: null
config_set: null
result_folder: null 
config_file_path: null
log_file_path: null
driving: True
