services:
  api_server:
    image: equitable_locations
    user: ${UID}:${GID}
    ports:
      - 8000:8000
    volumes:
      - ./logs:/app/logs
      - ./untracked:/app/untracked
    restart: unless-stopped