name: equitable-polls
channels:
    - conda-forge
    - nodefaults
dependencies:
    - python=3.11.4
    - pytest=9.0.3
    - pylint=4.0.5
    - scip=10.0.2 # C-library for pyscipopt
    - cython=3.2.4 # Build tool for pyscipopt
    - pyarrow=18.0.0
    - tqdm=4.67.0
    - geopandas=1.1.3
    - fiona=1.10.1
    - haversine=2.9.0
    - numpy=1.24.3
    - pandas=2.0.1
    - pyyaml=6.0.3
    - google-cloud-bigquery=3.40.1
    - pip
    - pip:
          - pyscipopt==6.1.0
          - pyomo==6.10.0
          - sqlalchemy==2.0.40
          - sqlalchemy-bigquery==1.16.0
          - alembic==1.13.3
          - google-cloud-bigquery-storage==2.27.0
          - googlemaps==4.10.0
