name: equitable-polls
channels:
  - conda-forge
dependencies:
  - python=3.11.4
  - jupyterlab=3.6.3
  - geopandas=0.9.0
  - numpy=1.24.3
  - haversine=2.8.0
  - pandas=2.0.1
  - pyomo=6.5.0
  - pyscipopt=4.3.0
  - pyyaml=6.0
  - tqdm=4.66.1
  - pytest=7.4.3
  - google-cloud-bigquery=3.25.0
  - google-cloud-bigquery-storage=2.25.0
  # - ast=0.0.2
  - arrow=1.3.0
  - db-dtypes=1.2.0
  - pip
  - pip:
    - -r requirements.txt

