name: equitable-polls
channels:
  - conda-forge
dependencies:
  - jupyterlab=3.6.3
  - geopandas=0.9.0
  - numpy=1.24.3
  - haversine=2.8.0
  - pandas=2.0.1
  - pyomo=6.5.0
  - pyscipopt=4.3.0
  - pyyaml=6.0
  - tqdm=4.66.1
