#Constants for the optimization function
location: Loudon_County_VA
year: 
  - '2024'
bad_types: 
    - 'bg_centroid' 
beta: -1
time_limit: 360000 #100 hours minutes
capacity: 1.2

####Optional#####
precincts_open: 14
max_min_mult: 5 #scalar >= 1
maxpctnew: 0 # in interval [0,1]
minpctold: .8 # in interval [0,1]