"""add log_distance

Revision ID: 450ad0516d66
Revises: d747d5c0f003
Create Date: 2024-11-24 19:39:17.775836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '450ad0516d66'
down_revision: Union[str, None] = 'd747d5c0f003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_configs', sa.Column('log_distance', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_runs', type_='foreignkey')
    # ### end Alembic commands ###
