config_set: DeKalb_County_GA_no_bg_school_configs_driving_pre_EV_2024
config_name: DeKalb_County_GA_precincts_open_24
location: DeKalb_County_GA
census_year: '2020'
year:
- '2020'
- '2022'
bad_types:
- Elec Day School - Potential
- bg_centroid
beta: -2
time_limit: 360000
capacity: 5
fixed_capacity_site_number: null
precincts_open: 24
max_min_mult: 5
maxpctnew: 1
minpctold: 0.75
driving: true
log_distance: false
penalized_sites: null
