config_set: Richmond_County_GA_log_configs_cap2_5
config_name: Richmond_County_GA_precincts_open_9
location: Richmond_County_GA
census_year: '2020'
year:
- '2020'
- '2022'
- '2024'
bad_types:
- Elec Day School - Potential
- bg_centroid
beta: -2
time_limit: 360000
capacity: 2.5
fixed_capacity_site_number: null
precincts_open: 9
max_min_mult: 5
maxpctnew: 1
minpctold: 0.8
driving: false
log_distance: true
penalized_sites: null
