config_set: Muscogee_County_GA_original_configs
config_name: Muscogee_County_GA_year_2020
location: Muscogee_County_GA
year:
- '2020'
bad_types:
- Elec Day Church - Potential
- College Campus - Potential
- Community Center - Potential
- Library - Potential
- Other - Potential
- bg_centroid
beta: -2
time_limit: 360000
capacity: 1.8
fixed_capacity_site_number: null
precincts_open: null
max_min_mult: 5
maxpctnew: 0
minpctold: 1
driving: false
log_distance: true
penalized_sites: null
