"""distances

Revision ID: 4a6823d917dd
Revises: 450ad0516d66
Create Date: 2025-02-27 11:04:21.825072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6823d917dd'
down_revision: Union[str, None] = '450ad0516d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distance_sets',
    sa.Column('id', sa.String(length=36), server_default=sa.text('GENERATE_UUID()'), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('location_type', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('census_year', sa.String(length=4), nullable=False),
    sa.Column('map_source_year', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distances',
    sa.Column('id', sa.String(length=36), server_default=sa.text('GENERATE_UUID()'), nullable=False),
    sa.Column('id_orig', sa.String(length=256), nullable=False),
    sa.Column('id_dest', sa.String(length=256), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.Column('distance_set_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['distance_set_id'], ['distance_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distances')
    op.drop_table('distance_sets')
    # ### end Alembic commands ###
