"""config and run updates

Revision ID: e5a21f261532
Revises: 3610b156d89e
Create Date: 2025-04-18 10:40:32.071236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a21f261532'
down_revision: Union[str, None] = '3610b156d89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_configs', sa.Column('census_year', sa.String(length=4), nullable=True))
    connection = op.get_bind()
    connection.execute(sa.text('UPDATE model_configs SET census_year = :value WHERE true'), {'value': '2020'})

    op.add_column('model_runs', sa.Column('polling_locations_set_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_runs', 'polling_locations_set_id')
    op.drop_column('model_configs', 'census_year')
    # ### end Alembic commands ###

