#Constants for the optimization function
location: DeKalb_GA
year: 
  - '2020'
bad_types: 
    - 'Elec Day School - Potential'
    - 'bg_centroid' 
beta: -1
time_limit: 360000 #100 hours minutes
capacity: 5

####Optional#####
precincts_open: 15
max_min_mult: 5 #scalar >= 1
maxpctnew: 1 # in interval [0,1]
minpctold: 0.6 # in interval [0,1]
driving: True