config_set: Muscogee_County_GA_tech_center_log_configs
config_name: Muscogee_County_GA_precincts_open_8
location: Muscogee_County_GA
census_year: '2020'
year:
- must_keep
bad_types:
- bg_centroid
beta: -2
time_limit: 360000
capacity: 1.8
fixed_capacity_site_number: null
precincts_open: 8
max_min_mult: 50000
maxpctnew: 1
minpctold: 1
driving: false
log_distance: true
penalized_sites: null
