#Constants for the optimization function
location: Norfolk_city_VA
year: 
  - '2024'
bad_types: 
    - 'bg_centroid' 
beta: -1
time_limit: 360000 #100 hours minutes
capacity: 1.8

####Optional#####
precincts_open: 12
max_min_mult: 5 #scalar >= 1
maxpctnew: 1 # in interval [0,1]
minpctold: .8 # in interval [0,1]
driving: True # bool (default = False)