config_set: Tarrant_County_TX_fair_capacity_2
config_name: Tarrant_County_TX_precincts_open_215
location: Tarrant_County_TX
census_year: '2020'
year:
- '2024'
- '2025'
bad_types:
- 'bg_centroid'
beta: -1
time_limit: 360000
capacity: 2
fixed_capacity_site_number: null
precincts_open: 215
max_min_mult: 5
maxpctnew: 0
minpctold: .5
driving: false
log_distance: true
penalized_sites: null