#Constants for the optimization function
location: Gwinnett_GA
year: '2022'
level: original
beta: -2
time_limit: 360000 #100 hours minutes
capacity: 5

####Optional#####
precincts_open: null
max_min_mult: 5 #scalar >= 1
maxpctnew: 0 # in interval [0,1]
minpctold: 1 # in interval [0,1]