#Constants for the optimization function
location: Gwinnett_GA
year: '2020'
bad_types: 
    - 'Election Day Loc - Potential'
    - 'College Campus - Potential'
    - 'Community Center - Potential'
    - 'Fire Station - Potential'
    - 'Library - Potential'
    - 'Other - Potential'
beta: -1
time_limit: 360000 #100 hours minutes
capacity: 5

####Optional#####
precincts_open: null
max_min_mult: 5 #scalar >= 1
maxpctnew: 0 # in interval [0,1]
minpctold: 1 # in interval [0,1]