#Constants for the optimization function
location: Gwinnett_GA
year: 
  - '2022'
bad_types: 
    - 'Election Day School - Potential'
    - 'Election Day Church - Potential'
    - 'Election Day Other - Potential'
    - 'College Campus - Potential'
    - 'Community Center - Potential'
    - 'Fire Station - Potential'
    - 'Library - Potential'
    - 'Other - Potential'
    - 'bg_centroid' 
beta: -1
time_limit: 360000 #100 hours minutes
capacity: 5

####Optional#####
precincts_open: null
max_min_mult: 5 #scalar >= 1
maxpctnew: 0 # in interval [0,1]
minpctold: 1 # in interval [0,1]